services:
    webapp:
    container_name: "webapp"
    build:
      context: .
      dockerfile: dockerfile
      arg:
        -  PASSWD: ${PASSWD}

      ports:
        - 80:80
    
      restart: always

    env_file:
          - .env
